name: Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - LICENSE-Apache
      - LICENSE-MIT

jobs:
  deploy:
    name: Deploy
    uses: time-rs/time-rs.github.io/.github/workflows/trigger-deploy.yaml@main
    secrets: inherit
    permissions:
      actions: write
